name: CI-integ-test

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
    - 'main'
    - 'release/**'
    - 'dev/**' # Allow running tests on dev branches without a PR

concurrency:
  group: integ-tests-${{ github.ref }}
  cancel-in-progress: false

permissions:
  contents: write

jobs:
  determine-suite:
    runs-on: ubuntu-latest
    outputs:
      runner-os: ${{ steps.determine-suite.outputs.suite == 'quick' && '["ubuntu-latest"]' || '["ubuntu-latest", "windows-latest", "macos-latest"]' }}
      cache-key-prefix: '0' # TODO DAZ Try this again ${{ steps.determine-suite.outputs.suite == 'quick' && '0' || github.run_number }}
      suite: ${{ steps.determine-suite.outputs.suite }}
    steps:
    - name: Determine suite to run
      id: determine-suite
      run: |
        # Always run quick suite if we are not in the core `gradle/actions` repository
        # This reduces the load for developers working on 'main' on forks
        if [ "${{ github.repository }}" != "gradle/actions" ]; then
          echo "Not in core repository: suite=quick"
          echo "suite=quick" >> "$GITHUB_OUTPUT"
          exit 0
        fi

        # Run full suite for push trigger with "[bot] Update dist directory" commit message
        if [ "${{ github.event.head_commit.message }}" == "[bot] Update dist directory" ]; then
          echo "Bot commit to main branch: suite=full"
          echo "suite=full" >> "$GITHUB_OUTPUT"
          exit 0
        fi

        # Run quick suite for everything else
        echo "Everything else: suite=quick"
        echo "suite=quick" >> "$GITHUB_OUTPUT"

  build-distribution:
    needs: [determine-suite]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v4
    - name: Build and upload distribution
      if: ${{ needs.determine-suite.outputs.suite != 'full' }}
      uses: ./.github/actions/build-dist

  caching:
    needs: [determine-suite, build-distribution]
    uses: ./.github/workflows/suite-integ-test-caching.yml
    with:
      runner-os: '${{ needs.determine-suite.outputs.runner-os }}'
      cache-key-prefix: '${{ needs.determine-suite.outputs.cache-key-prefix }}-'
      skip-dist: ${{ needs.determine-suite.outputs.suite == 'full' }}
    secrets: inherit

  other:
    needs: [determine-suite, build-distribution]
    uses: ./.github/workflows/suite-integ-test-other.yml
    with:
      runner-os: '${{ needs.determine-suite.outputs.runner-os }}'
      cache-key-prefix: '${{ needs.determine-suite.outputs.cache-key-prefix }}-'
      skip-dist: ${{ needs.determine-suite.outputs.suite == 'full' }}
    secrets: inherit
